version: '3.4'
services:
    app:
        container_name: main-app
        build:
            context: .
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
        command: yarn start:dev
        networks:
            - default
